### ISSUE TITLE
疫情诊断一栏有填写失误

### ISSUE THREAD

**Issue by Evphoria** [pkumath/yunzhanyi-autofill#1]
为我填写的是“医学观察”这个选项，不知道是不是我的选项排列有问题lol
![截屏2020-06-22 下午12 37 49](https://user-images.githubusercontent.com/39212324/85249051-4cc74800-b485-11ea-83a5-fe04197fc017.png)

**Comment by pkumath** [comment]
请问你是否使用的是最新的代码?

已知第一次上传的脚本确实有这个问题.
如果你使用的是最新的代码并出现此问题,那么你用的是什么浏览器?什么系统?然后使用chrome在”健康“这个选项右键,选择检查,并把出现的源代码截图

**Comment by pkumath** [comment]
哦哦,safari也可以直接检查,刚刚图片没有加载出来)

**Comment by Evphoria** [comment]
![截屏2020-06-22 下午1 45 36](https://user-images.githubusercontent.com/39212324/85252630-d0396700-b48e-11ea-82f6-069d80da49d5.png)
情况是这样~
然后我看到代码里有一行是：

`choice = '/html/body/div[2]/div[1]/div[1]/ul/li[0]/span'`

不知道是不是要改这里~

**Comment by Evphoria** [comment]
噢噢源代码是，
`choice = '/html/body/div[2]/div[1]/div[1]/ul/li[1]/span'`

我试着改了之后还没运行，不知道是怎么改23333

**Comment by pkumath** [comment]
https://whereby.com/pkumath <https://whereby.com/pkumath>

如果你方便的话,我们可以在这里看一下问题

**Comment by pkumath** [comment]
最新版本的代码已经做出了调整和修复
